[Desktop Entry]
Name=Shiki-Human + Vibrantly Simple
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Shiki-Human
MetacityTheme=Shiki-Colors-Striped-Metacity
IconTheme=Vibrantly-Simple-Dark-Orange
GtkColorScheme=fg_color:#101010,bg_color:#D8D8D8,base_color:#fff,text_color:#1A1A1A,selected_bg_color:#F7A145,selected_fg_color:#fff,tooltip_bg_color:#F5F5B5,tooltip_fg_color:#000,frame_color:#333333,inactive_frame_color:#333333
CursorTheme=default
CursorSize=18
NotificationTheme=Coco
