[Desktop Entry]
Name=Menta + Vibrantly Simple
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Menta
MetacityTheme=Menta
IconTheme=Vibrantly-Simple-Dark-Orange
GtkColorScheme=fg_color:#2c2c2c2c2c2c,bg_color:#dcdcdcdcdcdc,text_color:#2c2c2c2c2c2c,base_color:#f7f7f7f7f7f7,selected_fg_color:#f5f5f5f5f5f5,selected_bg_color:#bdcebdcebdce,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=mate
CursorSize=18
